In [1]:
#retriving from table
from sqlalchemy import create_engine
import pandas as pd

db_engine = create_engine("postgresql+psycopg2://postgres:123456@localhost:5432/global_debt_intelligence_hub")

countries_debt = pd.read_sql("SELECT * FROM countries_debt", db_engine)
all_countries = pd.read_sql("SELECT * FROM countries", db_engine)

In [ ]:
print(len(countries_debt))

In [ ]:
countries_debt.shape

In [ ]:
countries_debt.describe()

In [ ]:
countries_debt.describe(include = object)

In [10]:
region_debt =pd.merge(countries_debt,all_countries,on = 'country_code').groupby('region')["debt_amount"].mean().sort_values(ascending=False).reset_index()
region_debt

                       region   debt_amount
0         East Asia & Pacific  6.491771e+09
1                  South Asia  4.131529e+09
2   Latin America & Caribbean  2.638467e+09
3  Middle East & North Africa  1.576568e+09
4       Europe & Central Asia  1.561459e+09
5          Sub-Saharan Africa  6.116746e+08

In [7]:
region_debt =pd.merge(countries_debt,all_countries,on = 'country_code').groupby('region')["debt_amount"].sum().sort_values(ascending=False).reset_index()
region_debt

                       region   debt_amount
0         East Asia & Pacific  8.799271e+14
1   Latin America & Caribbean  5.694550e+14
2       Europe & Central Asia  2.569382e+14
3                  South Asia  2.322787e+14
4          Sub-Saharan Africa  2.250064e+14
5  Middle East & North Africa  1.755067e+14

In [6]:
import plotly.express as px

fig = px.bar(data_frame=region_debt,x="debt_amount",y="region",orientation="h",title="Total Debt by Countries Region",color="debt_amount",text="debt_amount")

NameError: name 'region_debt' is not defined

In [9]:
fig.show()

In [11]:
income_group_debt =pd.merge(countries_debt,all_countries,on = 'country_code').groupby('income_group')["debt_amount"].sum().sort_values(ascending=False).reset_index()
income_group_debt

          income_group   debt_amount
0  Upper middle income  1.671497e+15
1  Lower middle income  6.037064e+14
2           Low income  6.292042e+13
3          High income  9.884121e+11

In [12]:
fig = px.bar(data_frame=income_group_debt,x="debt_amount",y="income_group",orientation="h",title="Total Debt by Income Group",color="debt_amount",text="debt_amount")
fig.show()

In [15]:
lending_category_debt =pd.merge(countries_debt,all_countries,on = 'country_code').groupby('lending_category')["debt_amount"].sum().sort_values(ascending=False).reset_index()
lending_category_debt

  lending_category   debt_amount
0             IBRD  2.050080e+15
1              IDA  1.770355e+14
2            Blend  1.119963e+14

In [17]:
fig = px.bar(data_frame=lending_category_debt,x="debt_amount",y="lending_category",orientation="h",title="Total Debt by Lending Category",color="debt_amount",text="debt_amount")
fig.show()

In [18]:
external_debt_reporting_status_debt =pd.merge(countries_debt,all_countries,on = 'country_code').groupby('external_debt_reporting_status')["debt_amount"].sum().sort_values(ascending=False).reset_index()
external_debt_reporting_status_debt

  external_debt_reporting_status   debt_amount
0                         Actual  1.654517e+15
1                    Preliminary  6.287572e+14
2                       Estimate  5.583758e+13

In [19]:
fig = px.bar(data_frame=external_debt_reporting_status_debt,x="debt_amount",y="external_debt_reporting_status",orientation="h",title="Total Debt by external_debt_reporting_status",color="debt_amount",text="debt_amount")
fig.show()

In [20]:
all_countries['currency_unit'].unique()

<StringArray>
[          'Afghan afghani',             'Albanian lek',
           'Algerian dinar',           'Angolan kwanza',
           'Argentine peso',            'Armenian dram',
          'New Azeri manat',         'Bangladeshi taka',
         'Belarusian rubel',            'Belize dollar',
 ...
         'New Turkish lira',        'New Turkmen manat',
         'Ugandan shilling',        'Ukrainian hryvnia',
                'Uzbek som',             'Vanuatu vatu',
          'Vietnamese dong',              'Yemeni rial',
       'New Zambian kwacha', 'Zimbabwean Zimbabwe Gold']
Length: 102, dtype: str

In [4]:
#total debt by year
total_debt_by_year = countries_debt.groupby('debt_year')['debt_amount'].sum().sort_values(ascending=False).reset_index()
print(total_debt_by_year)

    debt_year   debt_amount
0        2024  1.666333e+14
1        2021  1.585789e+14
2        2023  1.585152e+14
3        2022  1.528388e+14
4        2020  1.418318e+14
5        2019  1.381037e+14
6        2018  1.339685e+14
7        2017  1.284443e+14
8        2014  1.138522e+14
9        2016  1.122608e+14
10       2013  1.055031e+14
11       2015  1.052631e+14
12       2012  9.727971e+13
13       2011  8.929955e+13
14       2010  7.925865e+13
15       2009  6.487490e+13
16       2008  6.360944e+13
17       2007  5.809243e+13
18       2006  4.837259e+13
19       2005  4.348131e+13
20       2004  4.114482e+13
21       2003  3.753339e+13
22       2000  3.364247e+13
23       2002  3.353026e+13
24       2001  3.319884e+13

In [8]:
#line charft of trend of total debt by year
fig = px.line(data_frame=total_debt_by_year,x="debt_year",y="debt_amount",title="Total Debt by Year",markers=True)
fig.show()

In [11]:
#Highest and lowest total debt country and amount
#merging all_countries and countries_debt to get country_name
all_countries = pd.merge(all_countries, countries_debt, on='country_code')
highest_debt_country = all_countries.groupby('country_name')['debt_amount'].sum().idxmax()
lowest_debt_country = all_countries.groupby('country_name')['debt_amount'].sum().idxmin()
highest_debt_amount = all_countries.groupby('country_name')['debt_amount'].sum().max()
lowest_debt_amount = all_countries.groupby('country_name')['debt_amount'].sum().min()

print(f"Highest debt country: {highest_debt_country} with amount: {highest_debt_amount}")
print(f"Lowest debt country: {lowest_debt_country} with amount: {lowest_debt_amount}")

Highest debt country: China with amount: 608388631633458.8
Lowest debt country: Tonga with amount: 84121740763.72

In [12]:
#find 7th rank of country  by total debt and its total debt amount
debt_ranks = all_countries.groupby('country_name')['debt_amount'].sum().sort_values(ascending=False)
seventh_rank_country = debt_ranks.index[6]  # Index 6 corresponds to the 7th rank
seventh_rank_amount = debt_ranks.iloc[6]  # Get the debt amount for the 7th rank

print(f"7th highest debt country: {seventh_rank_country} with amount: {seventh_rank_amount}")

7th highest debt country: Argentina with amount: 68754322224227.24